# Generated by Django 4.2.2 on 2023-10-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, null=True)),
                ('price', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('apple', 'Iphone'), ('samsung', 'Galaxy'), ('Google', 'Pixel')], default='apple', max_length=32)),
            ],
        ),
    ]
