# Generated by Django 4.2.2 on 2023-10-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_network_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='comment',
        ),
        migrations.AddField(
            model_name='network',
            name='data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('mobile', 'mobile'), ('home', 'home')], default='mobile', max_length=32),
        ),
        migrations.AddField(
            model_name='phone',
            name='cameras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='model',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('apple', 'Iphone'), ('samsung', 'Galaxy'), ('Google', 'Pixel'), ('other', 'other')], default='other', max_length=32),
        ),
    ]
