# Generated by Django 4.2.2 on 2023-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_phone_comment_network_data_network_lines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('Apple', 'Iphone'), ('Samsung', 'Galaxy'), ('Google', 'Pixel'), ('Other', 'other')], default='other', max_length=32),
        ),
    ]
